accounts/urls.py
from . import views
from django.conf.urls import url

app_name = 'accounts'
urlpatterns = [
    url('signup/', views.SignUp.as_view(), name='signup'),
    url('editprof/(?P<pk>[0-9]+)/', views.UserUpdate.as_view(), name='editprof'),
    url('users/', views.UserListView.as_view(), name='users_list'),
    url('user/follow/(?P<pk>[0-9]+)/', views.UserFollow.as_view(), name='user_follow'),
    url('userdetail/(?P<pk>[0-9]+)/', views.UserDetail.as_view(), name='userdetail'),
]

feed/urls.py
from . import views
from django.conf.urls import url

app_name = 'feed'
urlpatterns = [
    url('userfeed/', views.CreatePostView.as_view(), name='userfeed'),
    url('post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
]

hortihome/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'hortihome'

urlpatterns = [
url(r'^$', views.HomeView.as_view(), name='home'),
]

hortihub/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^accounts/', include('accounts.urls', namespace='accounts')),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^feed/', include('feed.urls', namespace='feed')),
    # url(r'^actions/', include('actions.urls', namespace='actions')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^', include('hortihome.urls',  namespace='hortihome')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, # not for prdocution use, used in debug
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ]

hortihome/models.py
from django.db import models

# Create your models here.

hortihome/views.py
from django.shortcuts import render
from django.views import View


class HomeView(View):
    template_name = 'hortihome/base.html'

    def get(self, request):
        return render(request, self.template_name)

templates/hortihome/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="HortiHub">
	<meta name="author" content="Chitranjali">
	<title>{% block title %}HortiHub{% endblock %}</title>
	<!-- Loads the path to static files -->
	{% load static %}
	<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>-->
	<script  src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
	<script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>

<body>
<div class="container-fluid">
	<nav class="navbar navbar-expand-sm navbar-custom navbar-light">
		<!-- Brand/logo -->
		<a class="navbar-brand custom" href="{% url 'feed:userfeed' %}"><h5>HortiHub</h5></a>
		<!-- Links -->
		{% if user.is_authenticated %}
		 <!-- Toggler/collapsibe Button -->
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar"><span class="navbar-toggler-icon"></span>
	  </button>
		<div class="collapse navbar-collapse" id="collapsibleNavbar">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'feed:userfeed' %}">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'accounts:users_list' %}">Users</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" href="{{ user.get_absolute_url }}">Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" href="#">Notifications</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'logout' %}">logout</a>
				</li>
			</ul>
		</div>
		{% endif %}
		
	</nav>
</div>

{% block body %}

{% endblock %}


<script>
{% block domready %}
{% endblock %}
</script>
</body>
</html>